
[colors.bright]
black   = "#121212"
blue    = "#83a598"
cyan    = "#8ec07c"
green   = "#b8bb26"
magenta = "#d3869b"
red     = "#fb4934"
white   = "#fbf1c7"
yellow  = "#fabd2f"

[colors.normal]
black   = "#000000"
blue    = "#458588"
cyan    = "#689d6a"
green   = "#98971a"
magenta = "#b16286"
red     = "#cc241d"
white   = "#a89984"
yellow  = "#d79921"

[colors.primary]
background = "#000000"
foreground = "#ebdbb2"

[cursor]
blink_interval = 500

[cursor.style]
blinking       = "Always"
shape          = "Beam"

[font]
size = 10

[font.normal]
family = "Cousine"

[general]
live_config_reload = true
